# ===================================================================
# dubbo config
# ===================================================================
dubbo:
  application:
    name: dubbo3-provider-service
  registry:
    address: nacos://localhost:8848
    timeout: 30000
    session: 30000
  protocol:
    name: tri